timeout: 3m

linters:
  disable-all: true
  enable:
    - goimports
    - gofmt
    - bodyclose
    - gosimple
    - prealloc
    - unused
    - govet
    - staticcheck
    - revive
    - ineffassign
    - whitespace
    - godot
    - gocyclo
    - misspell

issues:
  exclude-use-default: false