project_name: jobman

before:
  hooks:
    - go mod tidy
    - make gen-manpage gen-completions

builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - "386"
    main: ./main.go
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    binary: jobman

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

signs:
  - cmd: gpg
    args:
      - --output
      - $signature
      - --detach-sig
      - $artifact
    signature: ${artifact}.sig
    artifacts: none

changelog:
  sort: asc
  filters:
    exclude:
      - '^assets:'
      - '^docs:'
      - '^tests:'
      - '^site:'

release:
  github:
    owner: ryancswallace
    name: jobman
  draft: true
  prerelease: auto
  discussion_category_name: General
  header: |
    ## Features
    List of newly introduced features:
    - Item 1
    - Item 2
    ## Bug fixes
    List of fixed issues:
    - Item 1
    - Item 2
  footer: |
    ## Reference
    Read more on the [jobman documentation site](https://ryancswallace.github.io/jobman) and [jobman page](https://pkg.go.dev/github.com/ryancswallace/jobman) in the Golang reference.

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - LICENSE
      - etc/jobman/jobman.yml
      - docs/manpage/jobman.*
      - docs/completions/**/jobman

nfpms:
  - maintainer: ryancswallace <ryancswallace@gmail.com>
    description: "A command line job manager with flexible support for retries, timeouts, logging, notifications, and more."
    homepage: "https://github.com/ryancswallace/jobman"
    license: "MIT"
    formats:
      - deb
      - rpm
      - apk
    replacements:
      darwin: Darwin
    contents:
      - src: etc/jobman/jobman.yml
        dst: /etc/jobman/jobman.yml
        type: config
      - src: docs/manpage/jobman.1
        dst: /usr/share/man/man1
      - src: docs/completions/bash/jobman
        dst: /usr/share/bash-completion/completions/jobman
      - src: docs/completions/zsh/jobman
        dst: /usr/share/zsh/vendor-completions/_jobman

brews:
  - tap:
      owner: ryancswallace <ryancswallace@gmail.com>
      name: jobman
    name: jobman
    description: "A command line job manager with flexible support for retries, timeouts, logging, notifications, and more."
    homepage: "https://github.com/ryancswallace/jobman"
    license: "MIT"
    folder: formula
    commit_author:
      name: Ryan Wallace
      email: ryancswallace@gmail.com
    install: |
      bin.install "jobman"
      man1.install Dir["docs/manpage/jobman.1"]
      bash_completion.install "docs/completions/bash/jobman"
      zsh_completion.install "docs/completions/zsh/jobman"
    test: |
      system "#{bin/jobman}"