# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jobman < Formula
  desc "Reliably run command line jobs with flexible support for scheduling, retries, timeouts, logging, and notifications."
  homepage "https://github.com/ryancswallace/jobman"
  version "0.0.3-alpha"
  license "MIT"

  on_macos do
    url "https://github.com/ryancswallace/jobman/releases/download/v0.0.3-alpha/jobman_Darwin_x86_64.tar.gz"
    sha256 "055e94923b389061285c45abb472138ec2d378360057eb74701d5d6b76cccbb4"

    def install
      bin.install "jobman"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Jobman
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ryancswallace/jobman/releases/download/v0.0.3-alpha/jobman_Linux_x86_64.tar.gz"
      sha256 "a94752c9cb05205af4e3a17cb0b25afa3cd560164f977213fd9f56bdc718ecce"

      def install
        bin.install "jobman"
      end
    end
  end

  test do
    system "#{bin/jobman}"
  end
end
