# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jobman < Formula
  desc "A command line job manager with flexible support for retries, timeouts, logging, notifications, and more."
  homepage "https://github.com/ryancswallace/jobman"
  version "0.0.19"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ryancswallace/jobman/releases/download/v0.0.19/jobman_0.0.19_Darwin_arm64.tar.gz"
      sha256 "cbe7d6b5842f1eb713475863cbdcd25f0f1cf1f9a60da6933feba63db5887d19"

      def install
        bin.install "jobman"
        man1.install Dir["docs/manpage/jobman.1"]
        bash_completion.install "docs/completions/bash/jobman"
        zsh_completion.install "docs/completions/zsh/jobman"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ryancswallace/jobman/releases/download/v0.0.19/jobman_0.0.19_Darwin_x86_64.tar.gz"
      sha256 "0ad1b09f0db62e6ea17a3d52efe76033ebdea43c57f59f5c4c5620da1e4c6b9f"

      def install
        bin.install "jobman"
        man1.install Dir["docs/manpage/jobman.1"]
        bash_completion.install "docs/completions/bash/jobman"
        zsh_completion.install "docs/completions/zsh/jobman"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ryancswallace/jobman/releases/download/v0.0.19/jobman_0.0.19_Linux_x86_64.tar.gz"
      sha256 "69da3221e1b6c47f727516b6de26df06f8f12b46fb86b954a33a567cf4405073"

      def install
        bin.install "jobman"
        man1.install Dir["docs/manpage/jobman.1"]
        bash_completion.install "docs/completions/bash/jobman"
        zsh_completion.install "docs/completions/zsh/jobman"
      end
    end
  end

  test do
    system "#{bin/jobman}"
  end
end
