# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jobman < Formula
  desc "A command line job manager with flexible support for retries, timeouts, logging, notifications, and more."
  homepage "https://github.com/ryancswallace/jobman"
  version "0.0.7-alpha"
  license "MIT"

  on_macos do
    url "https://github.com/ryancswallace/jobman/releases/download/v0.0.7-alpha/jobman_0.0.7-alpha_Darwin_x86_64.tar.gz"
    sha256 "f53e54cac6018c94cc4f137c56f4f67da210f54346abf6fac3936b2cc0b9f63d"

    def install
      bin.install "jobman"
      man1.install Dir["docs/manpage/jobman.1"]
      bash_completion.install "docs/completions/bash/jobman"
      zsh_completion.install "docs/completions/zsh/jobman"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Jobman
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ryancswallace/jobman/releases/download/v0.0.7-alpha/jobman_0.0.7-alpha_Linux_x86_64.tar.gz"
      sha256 "1a4dc534de00def123efb819521738a47df7b5dc7d87fa4bcbb9aaa9c0a22244"

      def install
        bin.install "jobman"
        man1.install Dir["docs/manpage/jobman.1"]
        bash_completion.install "docs/completions/bash/jobman"
        zsh_completion.install "docs/completions/zsh/jobman"
      end
    end
  end

  test do
    system "#{bin/jobman}"
  end
end
