name: Build

on:
  push:
    branches: "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Lint
        uses: golangci/golangci-lint-action@v2
      - name: Test
        run: |
          go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
          # -s used to enable search in specified directory
          bash <(curl -s https://codecov.io/bash) -s .
          cat coverage.txt
      - name: Build
        run: |
          mkdir bin
          go build . -o ./bin/