name: Build

on:
  push:
    branches: "*"

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Lint
        uses: golangci/golangci-lint-action@v2

      - name: Test
        run: |
          go test -v -race -cover -coverprofile=coverage.txt -covermode=atomic ./...
          bash <(curl -s https://codecov.io/bash) -s .
          cat coverage.txt

      - name: Build
        run: |
          mkdir -p bin
          go build -o ./bin/ .