name: Test

on:
  push:
    branches: "*"

  pull_request:

  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Lint
        uses: golangci/golangci-lint-action@v2

      - name: Unit tests
        run: |
          go test -v -race -cover -coverprofile=coverage.txt -covermode=atomic ./...
          bash <(curl -s https://codecov.io/bash) -s .
          cat coverage.txt

      - name: End-to-end tests
        run: |
          true  # TODO: run tests/e2e/*

      - name: Performance tests
        run: |
          true  # TODO: run tests/perf/*

      - name: Test build
        run: |
          mkdir -p bin
          go build -o ./bin/ .