name: Update

on:
  schedule:
    # daily at 5:03 (randomly selected)
    - cron: '03 05 * * *'

  workflow_dispatch:

jobs:
  update:
    name: Copyright date
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run all update scripts
        run: |
          make update-all

    # TODO:
    # if changes...
    # commit changes on new branch b
    # create pull request for b -> main (e.g., https://github.com/peter-evans/create-pull-request)